accounts/urls.py
from django.urls import path, include
from accounts import views


app_name = 'accounts'

urlpatterns = [
    

    path('login/', views.login_view, name="login"),
    path('signup/', views.signup_view, name="signup"),
    path('<str:username>', views.perfil, name="account"),
    path('update/', views.editar, name="update"),
    path('update_user/', views.editar_usuario, name="account_update"),
    path('lista_usuarios/', views.lista_usuarios, name="user_list"),
    #path('staff_signup/', views.staffsignup_view, name="staff_signup"),
    path('logout/', views.logout_view, name="logout"),
    path('delete/', views.eliminar, name="delete_user"),

    #test stuff
    
    #path('update/', views.account_update, name="account_update")
]

proyecto_eneit/urls.py
from django.contrib import admin
from django.urls import path, include
from proyecto_eneit import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name="inicio"),
    path('accounts/', include('accounts.urls')),
    #path('tareas/', views.tareas, name="tareas"),
    path('crear_horario/', views.crear_horario, name="crear_horario"),
    path('calendario/', views.calendario_escolar, name="calendario"),
    path('editar_padre/', views.editar_padre, name="editar_padre"),
    path('editar_alumno/', views.editar_alumno, name="editar_alumno"),
    path('editar_profesor/', views.editar_profesor, name="editar_profesor"),
    path('editar_horario/', views.editar_horario, name="editar_horario"),
    path('editar_materia/', views.editar_materia, name="editar_materia"),

    path('horarios/', views.horarios, name="horarios"),
    path('mi_horario/', views.mi_horario, name="mi_horario"),
    
    
    path('eliminar_horario/', views.eliminar_horario, name="eliminar_horario"),
    path('eliminar_materia/', views.eliminar_materia, name="eliminar_materia"),
    path('eliminar_grupo/', views.eliminar_grupo, name="eliminar_grupo"),
    #grupos
     path('editar_grupo/<str:id_grupo>', views.editar_grupo, name="editar_grupo"),
    path('grupos/', views.lista_grupos, name="lista_grupos"),
    path('detalle_grupo/<str:id_grupo>', views.detalle_grupo, name="detalle_grupo"),
    path('crear_grupo/', views.crear_grupo, name="crear_grupo"),
   
    
    #alumnos
    path('alumnos/', views.lista_alumnos, name="lista_alumnos"),
    
    #padres
    path('padres/', views.lista_padres, name="lista_padres"),
    
    #profesores
    path('profesores/', views.lista_profesores, name="lista_profesores"),
    
    #materias
    path('materias/', views.lista_materias, name="lista_materias"),
    path('crear_materia/', views.crear_materia, name="crear_materia"),
    
    
    path('boleta/', views.boleta, name="boleta"),
    path('califs/', views.calif_parciales, name="califs")
]

accounts/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin 
from django.contrib.auth.base_user import BaseUserManager

class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, password=None, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('Se debe definir una matricula.')
        matricula = self.model.normalize_username(username)
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser debe tener su valor is_superuser=True')

        return self._create_user(username, password, **extra_fields)

class Usuario(AbstractBaseUser, PermissionsMixin):
    #username = None
    username = models.CharField(max_length=10, blank=False, primary_key=True, unique=True)
    nombre = models.CharField(max_length=20, blank=False)
    ap_pat = models.CharField(max_length=20, blank=True, null=True)
    ap_mat = models.CharField(max_length=20, blank=True, null=True)
    password = models.CharField(max_length=50)
    correo = models.EmailField(blank=True, null=True)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_parent = models.BooleanField(default=False)
    class Meta:
        permissions = (
            ("is_alumno", "Es Alumno"),
            ("is_profesor", "Es Profesor"),
            ("is_padre", "Es Tutor"),
        )

    objects = UsuarioManager()
    
    USERNAME_FIELD = 'username'
    
    REQUIRED_FIELDS = ['nombre']

# Create your models here.
class Alumno(models.Model):
    id_alumno = models.CharField(max_length=30, primary_key=True, default=None)
    profile = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    grupo = models.ForeignKey('proyecto_eneit.Grupo', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        db_table='Alumnos'
    
    def __str__(self):
        return str(self.id_alumno)

class Padre(models.Model):
    id_padre = models.CharField(max_length=30, primary_key=True, default=None)
    profile = models.ForeignKey(Usuario, blank=True, null=True, on_delete=models.CASCADE)
    hijos = models.ManyToManyField(Alumno, blank=True)
    rol_tutor = models.CharField(max_length=50, null=True)

    class Meta:
        db_table='Padres'

    def __str__(self):
        return str(self.id_padre)

class Profesor(models.Model):
    id_profesor = models.CharField(max_length=30, primary_key=True, default=None)
    profile = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    
    class Meta:
        db_table='Profesores'

    def __str__(self):
        return "Prof. "+str(self.profile.nombre)+" "+str(self.profile.ap_pat)+" "+str(self.profile.ap_mat)
    

accounts/forms.py
from django.db import models
from accounts.models import Alumno, Padre, Profesor, Usuario

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

class Signup_User(forms.ModelForm):
    def clean_matricula(self):
        username = self.cleaned_data.get('username').upper()
        r = Usuario.objects.filter(username=username)
        if r.count():
            raise ValidationError("Matricula ya existente")
        return username

    class Meta:
        model = Usuario
        fields = ['username', 'correo', 'password', 'nombre', 'ap_pat', 'ap_mat', 'is_student', 'is_parent', 'is_teacher']
        labels ={
            'username': 'Matricula',
            'nombre': 'Nombre',
            'ap_pat': 'Apellido Paterno',
            'ap_mat': 'Apellido Materno',
            'is_student': 'Estudiante',
            'is_parent': 'Padre, Madre o Tutor',
            'is_teacher': 'Profesor(a)',
        }
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean_password(self):
        password = self.cleaned_data.get('password')
        return password
    
    def save(self, commit=True):
        user = super(Signup_User, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ['username', 'correo', 'nombre', 'ap_pat', 'ap_mat', 'is_student', 'is_parent', 'is_teacher']
        labels = {
            'username': 'Matricula',
            'nombre': 'Nombre',
            'ap_pat': 'Apellido Paterno',
            'ap_mat': 'Apellido Materno',
            'is_student': 'Estudiante',
            'is_parent': 'Padre, Madre o Tutor',
            'is_teacher': 'Profesor(a)',
        }

class AlumnoForm(forms.ModelForm):
    class Meta:
        model = Alumno
        fields = ['grupo']

class PadreForm(forms.ModelForm):
    class Meta:
        model = Padre
        fields = ['hijos', 'rol_tutor']

class ProfesorForm(forms.ModelForm):
    class Meta:
        model = Profesor
        fields = []




accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from uuid import UUID
from accounts.models import Alumno, Padre, Profesor, Usuario
from accounts.forms import Signup_User , UserProfileForm, AlumnoForm, PadreForm, ProfesorForm #,Signup_Alumno, Signup_Padre, Signup_Profesor

# Create your views here.

#los diferentes tipos de perfiles solo iran en una view de perfil. para propositos de demo, iran en 3 diferentes.
#alumnos

def signup_view(request):
    if request.method=='POST':
        form = Signup_User(request.POST)
        if form.is_valid():
            #permission = Permission.objects.get(name='is_staff')
            
            new_user = form.save(commit=False)
            
            
            
            new_user.save()
            
            if new_user.is_student:
               # form2 = Signup_Alumno()
               Alumno.objects.create(profile=new_user, id_alumno = new_user.username)
               
            if new_user.is_teacher:
                Profesor.objects.create(profile=new_user, id_profesor = new_user.username)
                
            if new_user.is_parent:
                Padre.objects.create(profile=new_user, id_padre = new_user.username)
                
            #user.set_permissions.add(permission)
            #login(request, user)
            messages.success(request, 'Cuenta creada!')
            return redirect('accounts:signup') #HttpResponse('Success!')
    else:
        
        form = Signup_User()

    return render(request, 'signup.html', {'form': form})

#una login view para todos
def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                #return redirect('accounts:account', request.user.username)
                return redirect('inicio')
        else:
            messages.error(request, "Nombre de Usuario o contraseña incorrecta.")
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        #return redirect('accounts:login')
        return redirect('inicio')
        
    else:
        return HttpResponse('Not a POST request')

def lista_usuarios(request):
    users = Usuario.objects.all()
    return render(request, 'lista_usuarios.html', {'users': users})

def perfil(request, username):
    user = Usuario.objects.get(username=username)
    return render(request, 'perfil.html', {'user':user})

def editar(request):
    if request.method=="POST":
        user = request.user
        form = UserProfileForm(data=request.POST, instance=request.user)
        update = form.save(commit=False)
        
        update.save()
        return redirect('accounts:account', request.user)
    else:
        form=UserProfileForm(instance=request.user)
   
    return render(request, 'editar_perfil.html', {'form': form, 'user': user})

def editar_usuario(request):
    
    
    if request.method=="POST":
        user = Usuario.objects.get(username=request.POST.get('username'))
        form = UserProfileForm(data=request.POST, instance=user)
        update = form.save(commit=False)
        
        update.save()
        return redirect('accounts:user_list')
    else:
        user = Usuario.objects.get(username=request.GET.get('username'))
        form=UserProfileForm(instance=user)
   
    return render(request, 'editar_perfil.html', {'form': form, 'user':user})

def eliminar(request):
    username = request.POST.get('username')
    user = Usuario.objects.get(username=username)
    if request.method=="POST":
        
        user.delete()
        messages.success(request,'Usuario eliminado!')
    return redirect('accounts:user_list')


accounts/templates/accounts_index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Index Cuentas
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}


  {% include 'messages.html' %}
<ul>
{% foreach user in users %}
<li>{{user.username}}</li>
{% endforeach %}
</ul>


{% endblock %}

{% block scripts %}

{% endblock %}

accounts/templates/editar_perfil.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Editar Perfil
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}


  {% include 'messages.html' %}
  <h1>Usuario: {{ user.username }}</h1>
  <h3>{{user.nombre}} {{user.ap_pat}} {{user.ap_pat}}</h3>

  <form method="POST" action="{% url 'accounts:account_update' %}">
        {% csrf_token %}
     {{ form | bootstrap }}
     
     <button class="btn btn-primary" type="submit">Registrar</button>
     
     </form>

{% endblock %}

{% block scripts %}

{% endblock %}

accounts/templates/lista_usuarios.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Lista Horarios
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}


  {% include 'messages.html' %}
  <table class="table text-center table-hover">
      <thead>
          <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Roles</th>
        <th scope="col">acciones</th>
            </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.nombre }}</td>
            <td>{{ user.ap_pat }} {{ user.ap_mat }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.correo }}</td>
            <td>
                <ul>
                {% if user.is_student %}
                <li>Estudiante</li>
                {% endif%}
                {% if user.is_teacher %}
                <li>Profesor</li>
                {% endif%}

                {% if user.is_parent %}
                <li>Padre/Tutor</li>
                {% endif %}
                </ul>


            </td>
            <td>
                <div class="container d-flex justify-content-center">
                <form action = "." method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="username" value="{{ user.username }}">
                    <button class="btn btn-danger" formaction="{% url 'accounts:delete_user' %}"><i class="fa fa-trash"></i></button>
                
                
            </form>
            <form action = "." method="GET">
                    <input type="hidden" name="username" value="{{ user.username }}">
                    <button class="btn btn-success" formaction="{% url 'accounts:account_update' %}"><i class="fa fa-pen"></i></button>
                
            </form>
            </td>
        </div>
        </tr>
        {% endfor %}
    </tbody>
  </table>



{% endblock %}

{% block scripts %}

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Iniciar Sesión
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

<h1>Iniciar Sesión</h1>


  {% include 'messages.html' %}

  <form method="POST" action="{% url 'accounts:login' %}">
      {% csrf_token %}
   {{ form | bootstrap }}
   
   <button class="btn btn-primary" type="submit">Registrar</button>
   
   </form>

{% endblock %}

{% block scripts %}

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load bootstrap %}

{% block subtitle %}
Registro Alumno
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

<h1>Crear Cuenta</h1>

  {% include 'messages.html' %}


  <form method="POST" action="{% url 'accounts:signup' %}">
      {% csrf_token %}
   {{ form | bootstrap }}
   
   <button class="btn btn-primary" type="submit">Registrar</button>
   
   </form>

{% endblock %}

{% block scripts %}

{% endblock %}